### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [alanunruh/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by alanunruh** [comment]
I need to add the "viewport" meta tag to the <head>.

<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by alanunruh** [comment]
I need to add the "viewport" to the <head>

<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by alanunruh** [comment]
I need to add the "viewport" to the `<head>.`

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by Mikeysax** [comment]
:+1:
